---
- hosts: all
  become: yes # make sure you login to docker hub: docker login (normal namma14 account) and sudo docker login (root)
  gather_facts: no

  tasks:

    - name: create docker image using war file
      command: docker build -t simple-devops-image:latest .
      args:
        chdir: /opt/docker

    - name: create tag to image
      command: docker tag simple-devops-image namma/simple-devops-image

    - name: push image on to dockerhub
      command: docker push namma/simple-devops-image

    - name: remove docker images from ansible server
      command: docker rmi tomcat simple-devops-image:latest namma/simple-devops-image
      ignore_errors: yes
